version: '3.1'
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: tp2_compose
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "80:80"
    depends_on:
      - database